Adds compressed serialization for G2 points
paulmillr/noble-bls12-381 pull request #53
Opened 2022-06-10 20:00 UTC by christianpaquin

Adds compressed serialization for G2 points. I tried to copy the style of the G1 compressed serialization, but borrowed more from [Appendix C of the pairing-friendly curves draft](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-pairing-friendly-curves-10#appendix-C).

If this is desirable, I can continue work on this PR to harmonize the G1 and G2 code for this.

2022-06-11 16:36 UTC, paulmillr requested changes

2022-06-11 16:36 UTC, paulmillr commented on index.ts
> +    const m_byte = bytes[0] & 0xE0;
lowercase 0xe0 please

2022-06-11 16:36 UTC, paulmillr commented on index.ts
> +    if (m_byte == 0x20 || m_byte == 0x60 || m_byte == 0xE0) {
`===`

2022-06-11 16:36 UTC, paulmillr commented on index.ts
> +    const C_bit = m_byte & 0x80; // compression bit
`bitC`, `bitI`, `bitS`

2022-06-13 17:17 UTC, christianpaquin commented on index.ts
> +    if (m_byte == 0x20 || m_byte == 0x60 || m_byte == 0xE0) {
Done

2022-06-13 17:18 UTC, christianpaquin commented on index.ts
> +    const C_bit = m_byte & 0x80; // compression bit
Changed

2022-06-25 22:52 UTC, merged

2022-06-25 22:52 UTC, paulmillr commented
thanks